export let dat = [
    {
      id: 1,
      name: `Дюна`,
      author: `Фрэнк Герберт`,
      milk: `Cow`,
      since: `12th century AD`,
      type: `Semi-hard, hard`,
      mold: `No`,
      taste: `Round, spicy`,
      description: `Most popular semi-hard cheese`,
      tags: `semihard, hard, spicy, cow, mature, England`,
    },
  ]
  
  export const tags = [
    `young`,
    `mature`,
    `cow`,
    `sheep`,
    `goat`,
    `fresh`,
    `soft`,
    `semihard`,
    `hard`,
    `round`,
    `spicy`,
    `nutty`,
    `mellow`,
    `buttery`,
    `sweety`,
    `creamy`,
    `salty`,
    `mold`,
    `blue`,
    `Swiss`,
    `England`,
    `Italy`,
    `Spain`,
    `France`, 
  ];